_target_: src.models.hf_model.HFModelForCausalLM

model_name_or_path: EleutherAI/pythia-14m

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.LinearLR
  _partial_: true
